// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package grpcconnector_test

type mockFinder struct {
	GrpcURIsCalled chan bool
	GrpcURIsOutput struct {
		Ret0 chan []string
	}
}

func newMockFinder() *mockFinder {
	m := &mockFinder{}
	m.GrpcURIsCalled = make(chan bool, 100)
	m.GrpcURIsOutput.Ret0 = make(chan []string, 100)
	return m
}
func (m *mockFinder) GrpcURIs() []string {
	m.GrpcURIsCalled <- true
	return <-m.GrpcURIsOutput.Ret0
}
