#!/bin/sh

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="loggregator-certs"
mkdir -p ${depot_path}

# CA to distribute to loggregator clients and servers
certstrap --depot-path ${depot_path} init --passphrase '' --common-name loggregatorCA

# Server certificates for doppler
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name "doppler"
certstrap --depot-path ${depot_path} sign doppler --CA loggregatorCA

# Client certificates for metron agents
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name "metron_agent"
certstrap --depot-path ${depot_path} sign metron_agent --CA loggregatorCA
